// apps/app-vue/src/App.vue
<template>
  <div style="width: 100vw; height: 100vh"></div>

  <VisibilityWrapper
    selector="#watchedElement"
    @handleVisibility="handleVisibility"
  >
    <template #default="{ isVisible }">
      <div id="watchedElement">
        <p v-if="isVisible">Element is in view</p>
        <p v-else>Element is not in view</p>
      </div>
    </template>
  </VisibilityWrapper>
</template>

<script setup>
import { VisibilityWrapper } from "@holyfata/unlazy-vue";

const handleVisibility = (isVisible) => {
  console.log("Visible :", isVisible);
};
</script>

// apps/app-react/src/App.tsx
import VisibilityWrapper from "@holyfata/unlazy-react";

function App() {
  return (
    <div>
      <div className="app"></div>
      <VisibilityWrapper
        selector="#target-element"
        onVisibilityChange={(isVisible) =>
          console.log("Visibility changed:", isVisible)
        }
      >
        {({ isVisible }) => (
          <div id="target-element">
            {isVisible ? "Element is visible" : "Element is not visible"}
          </div>
        )}
      </VisibilityWrapper>
    </div>
  );
}

export default App;
