// packages/react-component-bundle/src/index.tsx
import React, { useEffect, useRef, useState } from "react";
import Monitor from "@holyfata/unlazy";

const VisibilityWrapper = (props: {
  selector: string;
  children: (props: { isVisible: boolean }) => React.ReactNode;
  onVisibilityChange?: (isVisible: boolean) => void;
}) => {
  const { selector, children, onVisibilityChange } = props;
  const [isVisible, setIsVisible] = useState(false);
  const monitorRef = useRef<Monitor | null>(null);

  useEffect(() => {
    const handleEnter = () => {
      setIsVisible(true);
      onVisibilityChange?.(true); // 触发事件并传递可见性状态
    };

    const handleLeave = () => {
      setIsVisible(false);
      onVisibilityChange?.(false); // 触发事件并传递可见性状态
    };

    monitorRef.current = new Monitor(selector, handleEnter, handleLeave);

    return () => {
      monitorRef.current?.disconnect();
    };
  }, [selector, onVisibilityChange]);

  return <>{children({ isVisible }) ?? undefined}</>;
};

export default VisibilityWrapper;

// packages/vue-component-bundle/src/index.vue
<template>
  <slot :is-visible="isVisible"></slot>
</template>

<script lang="ts">
import { defineComponent, onMounted, onUnmounted, ref } from "vue";
import Monitor from "@holyfata/unlazy";

export default defineComponent({
  name: "VisibilityWrapper",
  props: {
    selector: {
      type: String,
      required: true,
    },
  },
  emits: ["handleVisibility"], // 定义触发的事件
  setup(props, { emit }) {
    const isVisible = ref(false);
    let monitor: Monitor | null = null;

    const handleEnter = () => {
      isVisible.value = true;
      emit("handleVisibility", true); // 触发事件并传递可见性状态
    };

    const handleLeave = () => {
      isVisible.value = false;
      emit("handleVisibility", false); // 触发事件并传递可见性状态
    };

    onMounted(() => {
      monitor = new Monitor(props.selector, handleEnter, handleLeave);
    });

    onUnmounted(() => {
      if (monitor) {
        monitor.disconnect();
      }
    });

    return {
      isVisible,
    };
  },
});
</script>
